### ISSUE TITLE
Can' figure how to use reactivity & lists

### ISSUE THREAD

**Issue by archiloque** [WebReflection/uhtml#123]
Hello I'm learning to use uthml and there's something I can't figure out from the documentation because it's at the intersection of rendering, lists and reactivity.

My need can be seen like a classical TODO app:
- a list of items is editable by adding or removing elements from it
- each item of the list is itself editable by changing its content

What I want to do is to make the whole thing reactive, so when I use the UI the both type of data are updated (the list and the elements of the list).

I successfully implemented the first feature but fail at the second. It seems that I need to use computed signals from https://preactjs.com/guide/v10/signals/#computedfn, but the preact documentation is not very explicit, and I don't understand well enough how uhtml work to figure it out.

My current code looks like this:

```TypeScript
class Todos {
    constructor() {
    	this.items = [];
    	this.itemsSignal = signal(this.items);
	}

	renderItem(item: Item) {
		return html`something with item's values`;
	}

	renderItems() {
		const render = reactive(effect);
		render(this.tabElement, () => html`
			${this.itemsSignal.value.map((item) => this.renderItem(item))}
			// and a button that triggers addItem
		`);
	}
	addItem = (): void => {
        this.itemsSignal.value = [...this.itemsSignal.value, new Item()]
    }

}
```

I tried various things around creating a computed array from items and then make `renderItem` process these, but I don't get how to mix it with the `render` call because the documentation mention  a `computed` call around the thing and not uhtml's `html`.

Is there an idiomatic way to achieve this? Thanks!

**Comment by WebReflection** [comment]
I think you want *each* item to be reactive ... imagine editing just one item, the whole thing should re-render to atomically update that change, right?

In this scenario here one way to solve that (arguably an event based solution would be way easier to explain or reason about ... still ...)

  * each item is a signal, you can just update these a part and changes shold be reflected on the page/component
  * the list of items/signals is also a signal ... you change that list, the computed should reflect that change later on
  * the render uses a computed that returns that list of signals value and map each item in it so that when updates are needed, it will update the view accordingly

```js
class Todos {
  #items = signal([]);
  #computed;
  #effect;
  constructor() {
    this.#computed = computed(() => this.#items.value.map(item => this.renderItem(item)));
    this.#effect = effect(() => this.renderItems());
  }
  addItem(value) {
    this.#items.value = [...this.#items.value, signal(value)];
  }
  renderItem(item) {
    return html`<li>${item.value}</li>`;
  }
  renderItems() {
    render(this.tabElement, () => `<ul>${this.#computed.value}</ul>`);
  }
}
```

This is a simplification but it shows you where the *effect* makes sense, how to use computed to subscribe to your list of TODOs, and how each item update, once rendered, should also trigger the refresh of the list.

I hope this helps!

**Comment by archiloque** [comment]
Thanks for you detailed answer, it helped figuring out how it works, and I followed your suggestion to use events because it makes the code much easier to debug.
