### ISSUE TITLE
?checked radio type input issue

### ISSUE THREAD

**Issue by thipages** [WebReflection/uhtml#134]
Hi,

I have an issue with ?checked radio type input
I would like to clear inputs with no values set but this seems not possible with how I write it.
I think I understand it, since the attribute value is not changing but the checked property has been set

I reproduced a minimal example below (codepen [here](https://codepen.io/thipages/pen/yLdmXdR?editors=0011))
The real case is very similar : a series of questions are displayed one after the other, but the previous answer is kept ...

Thanks

Note : I have an ultimate workaround forcing a view reset `render(document.body, html``)` before renderng the inputs

```javascript

import {render, html } from 'https://cdn.jsdelivr.net/npm/uhtml/index.js';
const radio = (m) => {
  return html`
<label>
    <input type="radio" value=${m.value} name="name" ?checked=${m.checked} />
    ${m.label}
</label>
`
}
const radioGroup = (m) => {
    return html`
      ${m.map(v => radio(v))}
      <button @click=${update}>check</button>
    `
}
const data = [{checked: false, label:'nok', value:0}, {checked: false, label:'ok', value:1}]
function update() {
  render (document.body, radioGroup(data))
}
update()




```

**Comment by aries2004-bit** [comment]
try this
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by WebReflection** [comment]
it's an interesting catch-22 issue ... who's driving the data? it looks like you want to drive the data but then the user changes it (like it could any 3rd party library) and the logic does not update the state (the data array) when things changed *but* the live input does internally.

A few suggestions:

  * do not use `@` for accessors, use `.` instead ... that is `.checked=${m.checked}`
  * when a reset for fields is meant, use `form.reset()` which is the standard
  * it's not clear why you want to dictate and initial state that is not needed (radio don't get selected until they are) but you then don't care about data changes
  * it's not clear the overall intent/goal

The TL;DR is that state per each value is preserved (meomized) ... *maybe* I could add an extra `!` syntax to flag changes important, as in: "*run the update event no matter what, even if the data is the same as before*" but for that I need to think about ... otherwise I just changed `@` to `.` for `checked` and used this function:

```js
function update(event) {
  if (event) {
    event.preventDefault();
    event.currentTarget.closest('form').reset();
  }
  render (document.body, radioGroup(data))
}
```

This one works without any issue because it does reset the state and if you want to be sure a form is data driven, reset its state, render it with the updated data, and then submit it (or just submit it as that's latest state the user saw/meant).

**Comment by WebReflection** [comment]
I forgot to add the live working example: https://codepen.io/WebReflection/pen/oNrKorX?editors=0010

**Comment by thipages** [comment]
Thanks again for being clear and precise.
.... I should better know html standards anyway

Note : `@` should be replaced by `?` in the explanation in `do not use @ for accessors, use . instead ... that is .checked=${m.checked}`
