### ISSUE TITLE
Insert Element HTML

### ISSUE THREAD

**Issue by nndwn** [WebReflection/uhtml#136]
this library awesome and simple,  i want ask something about insert element html , i have structure html like this
```html 
<div class= 'sample'>
<p>sample text</p>
</div>
``` 
structure already render , sometime in js i create element insert in listerner like this
 
 ```js
 const mask = document.querySelector('.sample');
 mask.insertAdjacentHTML('beforeend', '<span></span>');
  ```
 so structure html change to 
 ```html
 <div class= 'sample'>
<p>sample text</p>
<span></span>
</div>
```

can this library do that ?

**Comment by WebReflection** [comment]
If you manually change something be sure it’s within a container so that no logic will try to diff that content. If you know already where new content will land though, put a comment or an empty string as placeholder and once you have data render it. Tags are also functions so that html can be passed as `html([str])` without you needing to use other primitives.

**Comment by nndwn** [comment]
> If you manually change something be sure it’s within a container so that no logic will try to diff that content. If you know already where new content will land though, put a comment or an empty string as placeholder and once you have data render it. Tags are also functions so that html can be passed as `html([str])` without you needing to use other primitives.

Thank you for answering, may i ask again for this

```html
<!--<>-->
<!--</>-->
```

how to remove it or how to add text like this 
```
<!--<start header>-->,
```
 im sorry actually im newbie 😅

**Comment by WebReflection** [comment]
you don't want to remove or change comments or the whole diffing logic breaks ... you can, however, write your own comments as part of the template but don't touch other comments:

  * these are irrelevant for layout size or performance
  * these are essential to pin-point fragments or nodes in places where these need to be diffed

touch that and goodbye *uhtml*.

**Comment by nndwn** [comment]
> you don't want to remove or change comments or the whole diffing logic breaks ... you can, however, write your own comments as part of the template but don't touch other comments:
> 
> * these are irrelevant for layout size or performance
> * these are essential to pin-point fragments or nodes in places where these need to be diffed
> 
> touch that and goodbye _uhtml_ (or _lit_ or any other library that is able to diff live).

thank you this interesting for me

**Comment by WebReflection** [comment]
if you need more details this is a meta description:

the template tag:
```js
const div = value => html`<div>a${value}c</div>`;

render(body, div(0));
```

produces:
```html
<div>a0<!---->c</div>
```

which is, behind the scene a div element with 4 child nodes:
  * a
  * 0
  * the comment
  * c

The diffing logic will apply a single update or node replacement if next time you have:

```js
render(body, div(1));
```

it uses the comment to diff its own associated list and then it uses `insertBefore` or `replace` accordingly with what you content you passed to the very same template.

It pin-points changes on the DOM in a way that:

  * it's 100% ignored by CSS
  * it's 100% ignored by any painting logic on the page ... it's literally a pin point with no side-effects on anything else
  * a comment can be anywhere, even between table rows, no other element (except maybe script or very few others with side-effects) can be placed to pin-point where changes will be applied.

When you see `<>` and `</>` it's a fragment instead, it happens when you have:

```js
html`
  <a />
  <b />
  <c />
`;
```

A fragment starts and ends because otherwise there's no way to understand its boundaries so start/close comments are there to reflect that fragment boundaries.
