### ISSUE TITLE
Question: Dynamic tags

### ISSUE THREAD

**Issue by thezealousfool** [WebReflection/uhtml#15]
Hi. Firstly, thanks for this library.

I had a use-case and was wondering if it is possible using uhtml.

Given a list of objects as:
```
elements = [{ tag: "div", content: "Hello" }, { tag: "h1", content: "World" }]
```
I would like to render nodes with the corresponding tag to a div for example.

I tried the following code and it (understandably) did not work.
```
render(
  this.element,
  html`${elements.map((elem) => html.node`<${elem.tag}>${elem.content}</${elem.tag}>`)}`
)
```

I was wondering if there is some way to achieve what I am looking for.

**Comment by WebReflection** [comment]
This is a recurrent question I've had for _hyperHTML_ and _lighterhtml_ too, but the short answer is that it's not possible with **non vDOM** libraries, simply because it's not possible to update/change a tag name in the wild. The logic behind these libraries is always the same: what operation that hole should result? ... and such operation should be supported by the platform.

You would need a reference per each node that uses such technique too, 'cause you must be able to swap on the fly possible different nodes.

The logic here is *very* different from SSR template engines, you're not working with strings, you are working with real HTML/SVG declarations, and a node that can be a `div` and suddenly a `p` makes no sense.

There are ways to work-around this scenario, but arguably the scenario is not needed in the first place, when you have a properly structured layout.

Using `eval` is also an option, but one I don't like.

As summary: in 3 years I've never needed this use case and I won't overly complicate the parsing and the runtime cost/performance to support such use case.

If this is vital for your application, I am afraid I suggest you look for something else not standards based.

Thanks for your understanding.

**Comment by WebReflection** [comment]
@thezealousfool maybe you'd be interested in knowing I've finally made it possible to pass arbitrary tag names at runtime:
https://github.com/WebReflection/static-params#readme

your example would work via ([CodePen](https://codepen.io/WebReflection/pen/MWKOQbp?editors=0010))
```js
import {render, html} from 'uhtml';
import {asStatic, asTag} from 'static-params';

const shtml = asTag(html);
const elements = [
  { tag: asStatic("div"), content: "Hello" },
  { tag: asStatic("h1"), content: "World" }
];

render(
  this.element,
  html`${elements.map((elem) => shtml`<${elem.tag}>${elem.content}</${elem.tag}>`)}`
);
```

**Comment by Dan-Do** [comment]
Hi @WebReflection
Could you help me look at this `insert dynamic element using insertAdjacentHTML`
https://codepen.io/ali33yukisakura/pen/PoOPqve?editors=0011

**Comment by WebReflection** [comment]
@Dan-Do the whole poin of projects like uhtml (or lit) is that you never want to manually interfere with the rendered content, but most importantly, **Never use innerHTML**.

Accordingly, this is probably what you want and, if you need to update that render, you need to put that render inside a callback you can call any time some state changes.
```js
import {render, html} from '//unpkg.com/uhtml?module';
import {asTag} from '//unpkg.com/static-params?module';

const shtml = asTag(html);
const buttonState = {disabled: false, text: 'Click Me'};
const {disabled, text} = buttonState;
const {log} = console;

const views = new Map();
let activeRoute = "/";
views.set('/', `<section route="/" class=${activeRoute == "/" ? "" : "is-hidden"}>Hello! + ${activeRoute == "/" ? "" : "is-hidden"}</section>`);
const loadedViews = ["/"];

render(document.body, html`
  <button class="clickable"
    onclick=${() => log('clicked')}
    ?disabled=${!disabled}
  >
    ${text}
  </button>
  ${loadedViews.includes("/") ? html([views.get("/")]) : html``}
`);
```
