### ISSUE TITLE
Handling null/undefined values in arrays

### ISSUE THREAD

**Issue by csabaxyz** [WebReflection/uhtml#32]
Hey,
I've been using uhtml in a project, and it's been great! Thank you for your great work!
I have one pet peeve though.
For example, you can have a ternary conditional to decide if you want to render a node or not, and `null` values are properly skipped over. Hovever, this doesn't work in arrays.
```js
const show = false
console.log(html.node`<div>${show ? html`<span>5</span>` : null}</div>`)
console.log(html.node`<div>${[html`<span>5</span>`, null]}</div>`)
```

The use-case is simple, I'd like to `.map` over an array and skip some items based on some condition.
Now, I know that I could have a `.filter` at the end, to filter out the null or undefined values. But maybe it'd make sense to handle the two cases the same way.
Right now the array case throws an error:
```
Uncaught TypeError: Cannot read property 'nodeType' of null
```

Also, this version results doesn't even result in the error, but in an incorrect tree:
```js
console.log(html.node`<div>${[undefined, html`<span>5</span>`]}</div>`)

// Returns:
// <div>,[object HTMLSpanElement]<!--isµ0--></div>
```

What do you think? Is this a bug or expected behavior?

**Comment by WebReflection** [comment]
in years of using this pattern, having holes in an array has never been a use case to me, and since that means *uhtml* should slow everything down because you pass invalid data, I think it's your responsibility to pass along arrays that *don't* contains holes, and I can't justify the usage of holes in an Array in any way:
  * is this one item? use ternary
  * is this an Array? be sure you don't have holes in it, and use filter yourself, because what you are asking is to use filter in core, and that's a performance hazard for the most common use cases where holes are not only undesired, but likely unexpected.

I hope my reasoning makes sense, feel free to ask more if needed 👋
