### ISSUE TITLE
Chrome fires blur event on node removal causing error when rendering on more than 1 callback

### ISSUE THREAD

**Issue by 50kudos** [WebReflection/uhtml#37]
Hi, thanks again for making uhtml, it's very stable! The following is browser specific issue, though uhtml could do thing that tolerates this rare problematic behaviour. 

This only happen on Chrome (tested on latest version):

When a node is removed, Chrome fires blur event on node removal, when we have another callback rendering html`` that causes node removed && added (re-attached), uhtml can throws this exception:

> Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?"

https://jsfiddle.net/um0kzdjx/31/
Inline:
```javascript
import {html, render} from "https://unpkg.com/uhtml@2.3.1/esm/index.js?module"

var items = [{key: "a"},{key: "b"}, {key: "c"}]
const renderItems = (items) => 
  html`
    <ul id="list">
      ${items.map((item, i) => html.for(item, item.key)`
      <li 
        tabindex="-1"
      	onblur="${e => rerender(items)}"
        onclick="${e => {
          items[i] = {...item, key: item.key + "_"} 
          rerender(items)
        }}"
      >
      	${item.key}
      </li>`)}
    </ul>
  `
 
const rerender = (items) => render(document.body, renderItems(items))
rerender(items)
```

---
This is not uhtml issue, so feel free to skip if it's considered unnecessary enhancement 😄 . (I fixed this by try not losing item reference, so no node removed). Thanks!

**Comment by WebReflection** [comment]
few things to consider:

  * don't use `html.for` ... there are really few cases it's necessary to have key events, and most of the time is not needed
  * as you use `html.for`, but you don't just change the key, you completely replace the `item`, I don't see any real-world use-case application of your test case
  * why wouldn't you instead show a `value` instead of needing to replace the item completely?

anyway, this looks like a bug to file in Chrome, as I've no idea how to feature-detect this shenanigan of Chrome, and the selling point of this library is that is both minimalistic, essential, and *small*, beside being extremely fast ... if I start fixing in core these things that don't even represent an interesting, or common, use case, this library will be bloated, it will require more code, more maintenance, and it will be slow, so I hope you don't mind if I *skip* this issue, but I'd like to thank you regardless for filing it, so that if there are any other weird cases like this, I *might* consider, or investigate, a proper fix that doesn't make everything slower for such little gain.

But then again, don't use keys or `html.for` unless you really have shared nodes across the app, but here nodes represented by item gets lost anyway, because you completely mutate it, so keyed lists like this are, imho, unnecessary, if not a mistake.

**Comment by 50kudos** [comment]
Thanks for explanation. I agreed. Just put a note here, sorry for misleading example, I only focus on reproducing the conflict rendering problem from 2 dom events. I actually need the `html.for` for list member deletion (I guess to auto keyed algorithm use some kind of index based, it gets weird sometimes for some operation on the list) and my actual app do not change key. And you are right that replacing `item` is not a good idea with using `html.for`. So I use `Object.assign` instead of `spread` op.

> minimalistic, essential, and small, beside being extremely fast

This is why uhtml is so cool ⚡
