### ISSUE TITLE
Functions no longer allowed as Holes?

### ISSUE THREAD

**Issue by gbishop** [WebReflection/uhtml#97]
In V3 we could pass a function into a template interpolation and the function would be called with the comment as an argument. This appears to be gone in V4. Am I correct?

**Comment by WebReflection** [comment]
Use ref attribute with a callback instead to know the node, otherwise please explain to me why that was useful. So far that pattern has lead to more troubles than it solves, and v4 was a “back to origins” release, and IIRC this breaking change was mentioned too. V3 is rock solid though, so if you really need that functionality feel free to stick with v3. I ma still curious to understand what’s your use case though

**Comment by gbishop** [comment]
It's been a while back but I think I used it because it was there. The ref
attribute is a better answer and works fine.

**Comment by WebReflection** [comment]
FYI the comment node is gone for non Array holes: cleaner output and less moving parts + fewer nodes around
